MONTHS = {
    'uk': ["Січень", "Лютий", "Березень", "Квітень", "Травень", "Червень",
           "Липень", "Серпень", "Вересень", "Жовтень", "Листопад", "Грудень"],
    'en': ["January", "February", "March", "April", "May", "June",
           "July", "August", "September", "October", "November", "December"],
    'hu': ["Január", "Február", "Március", "Április", "Május", "Június",
           "Július", "Augusztus", "Szeptember", "Október", "November", "December"],
}

STRINGS = {
    'uk': {
        'choose_lang': '🇺🇦 Оберіть мову / 🇬🇧 Choose language / 🇭🇺 Válasszon nyelvet:',
        'welcome': 'Привіт! Порахую доступну відпустку по місяцях.\n\n/calc — розрахунок\n/reset — очистити дані\n/cancel — скасувати',
        'ask_total': 'Скільки *годин відпустки* за рік? (напр. 168)',
        'ask_start_default': 'Початок відпусткового року — *Січень*. Змінити?',
        'btn_yes': 'Так', 'btn_no': 'Ні',
        'ask_end': 'Місяць *закінчення* контракту:',
        'ask_used': 'Скільки *днів* вже використано?',
        'ask_balance_yn': 'Є перенесений залишок або борг із попереднього контракту?',
        'btn_bal_yes': '✅ Так, є',
        'btn_bal_no': '❌ Ні',
        'ask_balance_val': 'Введи баланс у *годинах* (від\'ємне = борг, напр. `-24`):',
        'err_balance': 'Введи число (може бути від\'ємне, напр. -24 або 12).',
        'report_balance_line': 'Баланс-початок: {bal:+.1f} год ({bal_d:+.1f} дн)',
        'saved_prompt': 'Збережено: *{total}* год, {start}–{end}, баланс: {bal:+.1f} год.\nСкільки *днів* вже використано?',
        'reset_done': 'Параметри видалено. /calc запитає все заново.',
        'reset_none': 'Немає збережених даних.',
        'cancelled': 'Скасовано. /calc щоб почати знову.',
        'err_positive': 'Введи число більше 0 (напр. 168).',
        'err_nonneg': 'Введи 0 або більше (напр. 6).',
        'report_header': '📊 *Розрахунок відпустки*',
        'contract_line': 'Контракт: {start} – {end} ({dur} міс.)',
        'total_line': 'Усього: {total_h:.0f} год = {total_d:.1f} дн  |  Залишок: *{rem_d:.1f} дн*',
        'col_month': 'Місяць', 'col_accrued': 'Накоп', 'col_avail': 'Дост.',
        'disclaimer': '_Орієнтовно, не юридична консультація._',
        'calc_again': 'Ще раз — /calc',
    },
    'en': {
        'choose_lang': '🇺🇦 Оберіть мову / 🇬🇧 Choose language / 🇭🇺 Válasszon nyelvet:',
        'welcome': 'Hi! I will calculate your available vacation by month.\n\n/calc — calculate\n/reset — clear data\n/cancel — cancel',
        'ask_total': 'How many *vacation hours* per year? (e.g. 168)',
        'ask_start_default': 'Vacation year starts *January*. Change?',
        'btn_yes': 'Yes', 'btn_no': 'No',
        'ask_end': '*End* month of contract:',
        'ask_used': 'How many *days* already used?',
        'ask_balance_yn': 'Do you have a carried balance or debt from a previous contract?',
        'btn_bal_yes': '✅ Yes',
        'btn_bal_no': '❌ No',
        'ask_balance_val': 'Enter balance in *hours* (negative = debt, e.g. `-24`):',
        'err_balance': 'Enter a number (can be negative, e.g. -24 or 12).',
        'report_balance_line': 'Opening balance: {bal:+.1f} h ({bal_d:+.1f} d)',
        'saved_prompt': 'Saved: *{total}* h, {start}–{end}, balance: {bal:+.1f} h.\nHow many *days* already used?',
        'reset_done': 'Data cleared. /calc will ask everything again.',
        'reset_none': 'No saved data.',
        'cancelled': 'Cancelled. /calc to start again.',
        'err_positive': 'Enter a number greater than 0 (e.g. 168).',
        'err_nonneg': 'Enter 0 or more (e.g. 6).',
        'report_header': '📊 *Vacation Report*',
        'contract_line': 'Contract: {start} – {end} ({dur} months)',
        'total_line': 'Total: {total_h:.0f} h = {total_d:.1f} d  |  Remaining: *{rem_d:.1f} d*',
        'col_month': 'Month', 'col_accrued': 'Accr.', 'col_avail': 'Avail.',
        'disclaimer': '_Approximate, not legal advice._',
        'calc_again': 'Again — /calc',
    },
    'hu': {
        'choose_lang': '🇺🇦 Оберіть мову / 🇬🇧 Choose language / 🇭🇺 Válasszon nyelvet:',
        'welcome': 'Szia! Kiszámolom az elérhető szabadnapjaidat havonta.\n\n/calc — számítás\n/reset — adatok törlése\n/cancel — mégse',
        'ask_total': 'Hány *szabadságóra* jár évente? (pl. 168)',
        'ask_start_default': 'A szabadságév kezdete *Január*. Megváltoztatja?',
        'btn_yes': 'Igen', 'btn_no': 'Nem',
        'ask_end': 'A szerződés *vége* melyik hónapban?',
        'ask_used': 'Hány *napot* vett már ki?',
        'ask_balance_yn': 'Van átvitt egyenleg vagy tartozás az előző szerződésből?',
        'btn_bal_yes': '✅ Igen',
        'btn_bal_no': '❌ Nem',
        'ask_balance_val': 'Add meg az egyenleget *órában* (negatív = tartozás, pl. `-24`):',
        'err_balance': 'Írj be egy számot (lehet negatív, pl. -24 vagy 12).',
        'report_balance_line': 'Nyitó egyenleg: {bal:+.1f} óra ({bal_d:+.1f} nap)',
        'saved_prompt': 'Mentve: *{total}* óra, {start}–{end}, egyenleg: {bal:+.1f} óra.\nHány *napot* vett már ki?',
        'reset_done': 'Adatok törölve. A /calc mindent újra kérdez.',
        'reset_none': 'Nincs mentett adat.',
        'cancelled': 'Megszakítva. /calc az újrakezdéshez.',
        'err_positive': 'Adjon meg 0-nál nagyobb számot (pl. 168).',
        'err_nonneg': 'Adjon meg 0-t vagy annál nagyobb számot (pl. 6).',
        'report_header': '📊 *Szabadság kalkulátor*',
        'contract_line': 'Szerződés: {start} – {end} ({dur} hó)',
        'total_line': 'Összesen: {total_h:.0f} óra = {total_d:.1f} nap  |  Maradék: *{rem_d:.1f} nap*',
        'col_month': 'Hónap', 'col_accrued': 'Felhalm.', 'col_avail': 'Elérh.',
        'disclaimer': '_Tájékoztató jellegű, nem jogi tanácsadás._',
        'calc_again': 'Újra — /calc',
    },
}
